services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educampus_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_EduCampus
      DB_USERNAME: root
      DB_PASSWORD: root123

  vite:
    image: node:24
    container_name: educampus_vite
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  mysql:
    image: mysql:8.4
    container_name: educampus_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_EduCampus
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - educampus_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  educampus_mysql_data:

